JSREPL::Languages::QBasic =
  name: 'Quick Basic'
  category: 'Imperative'
  scripts: [
    'extern/qb.js/RuleSet.js'
    'extern/qb.js/RuleParser.js'
    'extern/qb.js/Types.js'
    'extern/qb.js/VirtualMachine.js'
    'extern/qb.js/TypeChecker.js'
    'extern/qb.js/EarleyParser.js'
    'extern/qb.js/GlrParser.js'
    'extern/qb.js/Tokenizer.js'
    'extern/qb.js/CodeGenerator.js'
    'extern/qb.js/QBasic.js'
    'langs/qbasic/jsrepl_qbasic.js'
  ]
  example_file: 'langs/qbasic/examples.txt'
  help_link: 'http://westcompsci.pima.edu/cis100/'
  extension: 'bas'
  logo: 'langs/qbasic/logo.png'

JSREPL::Languages::Lisp =
  name: 'Lisp'
  category: 'Functional'
  scripts: [
    'langs/lisp/BPWJs.js'
    'langs/lisp/Atom.js'
    'langs/lisp/UnevaluatedObj.js'
    'langs/lisp/JavathcriptTokenizer.js'
    'langs/lisp/JavathcriptParser.js'
    'langs/lisp/Environment.js'
    'langs/lisp/Javathcript.js'
    'langs/lisp/DocumentEvaluator.js'
    'langs/lisp/jsrepl_lisp.js'
  ]
  example_file: 'langs/lisp/examples.txt'
  help_link: 'http://en.wikipedia.org/wiki/Lisp_(programming_language)'
  extension: 'lisp'
  logo: 'langs/lisp/logo.jpg'

JSREPL::Languages::Scheme =
  name: 'Scheme'
  category: 'Functional'
  scripts: [
    'lib/prototype-1.6.0.3.js'
    'extern/biwascheme/src/stackbase.js'
    'extern/biwascheme/src/set.js'
    'extern/biwascheme/src/write.js'
    'extern/biwascheme/src/pair.js'
    'extern/biwascheme/src/value.js'
    'extern/biwascheme/src/symbol.js'
    'extern/biwascheme/src/char.js'
    'extern/biwascheme/src/number.js'
    'extern/biwascheme/src/port.js'
    'extern/biwascheme/src/record.js'
    'extern/biwascheme/src/hashtable.js'
    'extern/biwascheme/src/syntax.js'
    'extern/biwascheme/src/types.js'
    'extern/biwascheme/src/parser.js'
    'extern/biwascheme/src/compiler.js'
    'extern/biwascheme/src/pause.js'
    'extern/biwascheme/src/call.js'
    'extern/biwascheme/src/interpreter.js'
    'extern/biwascheme/src/infra.js'
    'extern/biwascheme/src/r6rs_lib.js'
    'extern/biwascheme/src/webscheme_lib.js'
    'extern/biwascheme/src/extra_lib.js'
    'extern/biwascheme/src/srfi.js'
    'langs/scheme/jsrepl_scheme.js'
  ]
  example_file: 'langs/scheme/examples.txt'
  help_link: 'http://en.wikipedia.org/wiki/Scheme_(programming_language)'
  extension: 'scm'
  logo: 'extern/biwascheme/website/images/biwascheme_logo.png'
